name: Terraform Reusable Workflow

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'The working directory to run Terraform commands from'
        required: true
        type: string
      environment:
        description: 'The environment to target (e.g., production, staging).'
        required: true
        type: string
      tfvars_project_name:
        description: 'The name of the project in the environments directory (e.g., customer-abc19a39).'
        required: true
        type: string
      gcp_project_id:
        description: 'The target Google Cloud Project ID (e.g., caddi-us-c-abc19a39-prd).'
        required: true
        type: string
    secrets:
      GCP_SA_KEY:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD_PROJECT: ${{ inputs.gcp_project_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ${{ inputs.working_directory }}
          soft_fail: true # Allow tfsec to fail without failing the job

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Run tflint
        working-directory: ${{ inputs.working_directory }}
        run: tflint --no-color

      - name: Terraform Format Check
        working-directory: ${{ inputs.working_directory }}
        run: terraform fmt -check=true

      - name: Terraform Validate
        working-directory: ${{ inputs.working_directory }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ inputs.working_directory }}
        run: |
          terraform plan -no-color -var-file=./${{ inputs.environment }}/terraform.tfvars